### ISSUE TITLE
Create greentea-client-tiny (base C implementation of this module)

### ISSUE THREAD

**Issue by PrzemekWirkus** [ARMmbed/greentea-client#1]
Changes:
- Move and maintain `greentea-client-tiny` module in C (no C++).
- Add this as an dependency to `greentea-client` which will be a C++ wrapper for `greentea-client-tiny`.

**Comment by PrzemekWirkus** [comment]
There is repo stub which should be used to store implementation of `greentea-client-tiny` here: https://github.com/ARMmbed/greentea-client-tiny

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*
