### ISSUE TITLE
Add support for no __sync transactions

### ISSUE THREAD

**Issue by PrzemekWirkus** [ARMmbed/greentea-client#16]
### Description

Developers want to debug tests but at the same time they do not want to send `__sync` packet to device.
This is response for https://github.com/ARMmbed/greentea/issues/103. I've already added support for `--sync` command line switch to htrun, see [here](https://github.com/ARMmbed/htrun/releases/tag/v0.2.18).

What we want?
- Some simple way to disable in `greentea-client` `__sync` packet support (blocking read on `stdin` for `__sync`).
- Support work-flow where developers:
  - Build tests with no `__sync` support.
  - Run `mbedhtrun` with `--sync 0` to skip sending `__sync`.
  - Debug with host tests.

@adbridge FYI

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2830

**Comment by adbridge** [comment]
*Jira reference: https://jira.arm.com/browse/IOTSFW-2830*

**Comment by adbridge** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTSFW-2830*
