### ISSUE TITLE
v0.1.6 breaks existing tests

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/greentea-client#3]
Removing the definition of `NL` causes existing tests not to compile.

https://github.com/ARMmbed/greentea-client/commit/fa5e421f0de5e3ee344c1036a92d6f0463687466?diff=unified#diff-798846f44ff6b4b0c228a058d7c3e149L23

cc @PrzemekWirkus

**Comment by PrzemekWirkus** [comment]
Patch released with version [v0.1.7](https://github.com/ARMmbed/greentea-client/releases/tag/v0.1.7).

**Comment by bremoran** [comment]
Thank you, this patch resolves the issue.
